dist: trusty
sudo: required
language: ruby # for Jekyll
ruby:
  - 2.2
gemfile: gh-pages/Gemfile
before_install:
  - |
    sudo apt-get install -qq --no-install-recommends texlive \
      texlive-latex-extra texlive-xetex \
      latex-beamer ghostscript \
      fonts-lmodern fonts-droid fonts-noto
  - xelatex --version
script:
  - env LECTURE_FONTS=noto+droid make gh-build
