dist: trusty
sudo: required
language: ruby # for Jekyll
rvm:
  - 2.2
gemfile: gh-pages/Gemfile
cache: bundler
branches:
  only:
    - master
    # tags
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
before_install:
  - |
    sudo apt-get install -qq --no-install-recommends texlive \
      texlive-latex-extra texlive-xetex \
      latex-beamer ghostscript \
      fonts-lmodern fonts-droid fonts-noto
  - xelatex --version
script:
  - make LECTURE_FONTS=noto+droid -j 2 all-beamer
  # On this step, we want to test a Jekyll build only, hence the NOFILES flag.
  # We shouldn't care if the previous step fails
  - make GH_PAGES_NOFILES=1 gh-build
